apiVersion: v1
entries:
  jenkins-operator:
  - apiVersion: v1
    appVersion: 0.2.2
    created: "2019-10-21T14:38:09.99789724+02:00"
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: 0ca2904d3971422e31ef3ca986ba6123ffb264d4dd938be4361a22114205789d
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: 0.2.2
    created: "2019-10-21T14:38:09.998761996+02:00"
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: b0074d3ded2fdaad529c9079503eb82bb9c8cfb90fd8b60d09c8d9899f36d78f
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator/jenkins-operator-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2019-10-21T14:38:09.998283581+02:00"
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: d5828cba35e435fc6526d235ec98b3ffdb8d6ed20b82c953a81a5c1f660d1fb3
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator/jenkins-operator-0.0.1.tgz
    version: 0.0.1
generated: "2019-10-21T14:38:09.996949076+02:00"
