apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: example
spec:
  master:
   image: jenkins/jenkins:lts
   readinessProbe:
     httpGet:
       path: /login
       port: 8080
       scheme: HTTP
     failureThreshold: 10
     initialDelaySeconds: 30
     periodSeconds: 10
     successThreshold: 1
     timeoutSeconds: 5
   livenessProbe:
     httpGet:
       path: /login
       port: 8080
       scheme: HTTP
     initialDelaySeconds: 35
     failureThreshold: 10
     periodSeconds: 10
     successThreshold: 1
     timeoutSeconds: 5
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
