## Append samples you want in your CSV to this file as resources ##
resources:
- jenkins_v1alpha2_jenkins.yaml
- jenkins_v1alpha2_jenkinsimage.yaml
- jenkins_v1alpha2_backupworker.yaml
- jenkins_v1alpha2_backup.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
